import Head from "next/head";
//hooks
import { useRouter } from "next/router";
//components
import { Input } from "@/components/Input/Input";
//styles
import styles from "@/styles/Home.module.css";

import { Socket } from "socket.io-client";

type GameModeProps = {
  socket: Socket;
  handleMode: Function;
  playerName: string;
};

export default function GameMode({ handleMode, playerName }: GameModeProps) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Bingo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>bingo</h1>
        <h2 className={styles.text}>Hi {playerName}</h2>
        <h2 className={styles.text}>The game will shortly start after the lobby gets enough players</h2>

        
      </main>
    </>
  );
}
