import Head from 'next/head'
//hooks
import { useRouter } from 'next/router'
//components
import { Input } from '@/components/Input/Input'
//styles
import styles from '@/styles/Home.module.css'

export default function Home() {

  const router = useRouter();

  const handleScreen = () => {
    router.push('/game')
  }

  return (
    <>
      <Head>
        <title>Bingo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>bingo</h1>
        <h2 className={styles.text}>start game</h2>
        <div className={styles.form}>
          <Input label="Put your name" type="text" />
          <button onClick={handleScreen}></button>   
        </div>
      </main>
    </>
  )
}
